version: '3.9'

services:

  mysql:
    image: mysql:8.4
    container_name: ecommerce-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce_db
      MYSQL_USER: ecommerce
      MYSQL_PASSWORD: ecommerce123
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - ecommerce-network

  login-service:
    build: ./login-service
    container_name: login-service
    depends_on:
      - mysql
    ports:
      - "8081:8081"
    networks:
      - ecommerce-network

  product-service:
    build: ./product-service
    container_name: product-service
    depends_on:
      - mysql
    ports:
      - "8082:8082"
    networks:
      - ecommerce-network

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    depends_on:
      - login-service
      - product-service
    ports:
      - "8080:8080"
    networks:
      - ecommerce-network

volumes:
  mysql-data:

networks:
  ecommerce-network:
    driver: bridge
